server:
  port: 9091

spring:
  application:
    name: msvc-appointment

  r2dbc:
    url: r2dbc:h2:mem:///appointmentdb;MODE=PostgreSQL
    username: sa
    password: sasa

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

logging:
  level:
    org.springframework.r2dbc.connection: DEBUG