server:
  port: 8090

spring:
  application:
    name: msvc-paciente
  messages:
    basename: message-error
    encoding: UTF-8

  r2dbc:
    url: r2dbc:h2:mem:///patientdb;MODE=PostgreSQL
    username: sa
    password: sasa

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

logging:
  level:
    org.springframework.r2dbc.connection: DEBUG